String[] references = {"langauge icon - https://cdn2.iconfinder.com/data/icons/social-productivity-line-art-2/128/world-512.png",
"wifi icon - https://icons8.com/web-app/171/wi-fi",
"wifi level icons - //http://simpleicon.com/sets/signal/page/2/",
"app icon - http://i.imgsafe.org/bc2015d4a8.png", 
"setting icon - http://iconshow.me/media/images/ui/ios7-icons/png/512/gear.png", 
"movement icon - https://www.iconfinder.com/icons/237454/arrow_cursor_move_icon",
"trash icon - https://thenounproject.com/term/trash-can/425731/",
"weather app icon - http://www.freeiconspng.com/icons/weather-icon-png",
"music app icon - https://www.iconfinder.com/icons/820103/love_love_music_music_music_note_sing_wedding_music_icon", 
"health app icon - https://thenounproject.com/term/health/4215/",
"calendar app icon - https://thenounproject.com/term/calendar/",
"news app icon - https://www.iconfinder.com/icons/112154/headlines_news_newspaper_print_text_icon",
"timer app icon - https://icons8.com/web-app/1111/timer",
"stopwatch app icon - https://thenounproject.com/term/stopwatch/141007/",
"note app icon - https://www.iconfinder.com/icons/261628/document_modify_note_notes_paper_pencil_record_icon",
"email app icon - http://www.freeiconspng.com/icons/email-icon",
"twitter app icon - http://www.iconarchive.com/show/socialmedia-icons-by-uiconstock/Twitter-icon.html", 
"instagram app icon - https://www.reddit.com/r/Android/comments/4j7x3w/material_instagram_icons/",
"facebook app icon - http://www.business2community.com/small-business/social-media-beneficial-small-business-owners-5-sites-best-ways-use-01772814#bvFfklVSsoJosYYG.97",
"sunny weather icon - https://www.iconfinder.com/icons/317415/blue_sky_clear_forecast_sun_sunny_weather_icon",
"cloudy weather icon - https://www.iconfinder.com/icons/214293/cloud_clouds_cloudy_saas_weather_icon",
"gmail email icon - https://cdn4.iconfinder.com/data/icons/free-colorful-icons/360/gmail.png",
"calendar - http://www.free-printable-calendar.com/printable-calendar-images/april-2017-printable-calendar.gif",
"cnn icon - http://www.siriusxm.com/cmds/displayLogo?key=cnn&imageType=16",
"reuters icon - https://pbs.twimg.com/profile_images/806242452528975872/noWUmHen.jpg",
"google news icon - https://uappexplorer.com/api/icon/320d6f32c23cc7e4197b42df9d625d18/googlenews.mreese.png",
"play button - https://thenounproject.com/term/play/10681/",
"forward button  - http://www.flaticon.com/free-icon/step-forward-control-button-symbol-of-triangular-right-arrow-pointing-a-vertical-line_37075",
"pause button - https://www.iconfinder.com/search/?q=pause",
"scale icon - http://www.freeiconspng.com/icons/scale-icon",
"walking icon - https://thenounproject.com/term/walking/35091/",
"sleep icon - https://www.iconfinder.com/icons/573088/apple_disturb_good_moon_night_sleep_stars_icon",
"instagram image 1 - http://blog.instagram.com/post/27128108925/the-scoop-on-food-photography-want-to-see-more",
"instagram image 2 - http://68.media.tumblr.com/211ebcb3e7761aa53eb02da02644ac55/tumblr_mrfnzdT6lI1qj08ewo1_1280.jpg",
"instagram image 3 - http://blog.instagram.com/post/79690139772/locallensbelohorizonte",
"cnn 1 - http://koreajoongangdaily.joins.com/news/article/article.aspx?aid=3032113",
"cnn 2 - http://ew.com/movies/2017/04/12/harry-potter-dumbledore-jude-law/",
"reuters 1 - http://www.hollywoodreporter.com/news/charlie-murphy-dead-comedian-was-57-993220",
"reuters 2 - https://www.washingtonpost.com/news/morning-mix/wp/2017/04/12/dear-cosmopolitan-magazine-cancer-is-not-a-diet-plan/",
"reuters 3 - http://www.sfgate.com/national/article/Boy-8-drives-sister-4-to-McDonald-s-for-a-11068868.php",
"google 1 - https://www.theweathernetwork.com/news/articles/trump-rids-ban-on-hunting-bears-and-wolves-in-alaska-refuges/81051/",
"google 2 - https://www.usatoday.com/story/news/2017/04/07/employee-accidentally-shoots-hurts-self-nra-museum/100192128/",
"google 3 - https://www.usatoday.com/story/news/2017/04/08/hacker-triggers-all-156-emergency-sirens-dallas/100212412/"};